### ISSUE TITLE
Should we require login to see the / route?

### ISSUE THREAD

**Issue by kazemicode** [auth0-training/labs-node-create-an-application#13]
Seems like users should be able to visit the `/` route without being prompted for authN. To do this, we must update the `auth` router config in `index.js` with:

`authRequired: false`

This attribute controls whether or not authN is required for ALL routes.

https://auth0.com/docs/quickstart/webapp/express/interactive

**Comment by NotMyself** [comment]
The lab material eventually walks them through that process.

**Comment by kazemicode** [comment]
Yeah, I saw that as I proceeded. Just wasn't sure if it would make sense to start out with that as the default behavior or not. This was more of a note for discussion as we begin to test through the labs for ILT. I totally get the decision for adding it later in order to call it out to the learner.
