### ISSUE TITLE
Step 4: Create .env file fails

### ISSUE THREAD

**Issue by arcadia-okta** [auth0-training/labs-node-create-an-application#21]
### Description

I believe that I have successfully followed all of the steps in this tour up to and through step 4, barring the creation of the `.env` file.

<img width="975" alt="image" src="https://github.com/auth0-training/labs-node-create-an-application/assets/141176904/a9a6bf44-5476-4127-9628-1ff0ecef7f6f">

![image](https://github.com/auth0-training/labs-node-create-an-application/assets/141176904/a613c444-b40e-4f61-96f5-0ba3a440f2e1)

As far as I have been able to tell, I have not run into any issues setting up and connecting the environment. 

### Reproduction

- Follow the instructions up to step 4 and configure the local environment.
- Click the two links in order.

### Environment

Just work from the cloned repo.

**Comment by kazemicode** [comment]
Hi @arcadia-okta 
It looks like your Lab: Web App is created in your labs-arcadia-rose-okta tenant. However, in VSCode, you are connected to a different tenant named arcadia-rose-okta. This is why the .env file is not getting generated. To remedy this, while in VSCode, bring up the Command Palette by holding down Command + Shift + P. Type in "Auth0" and select the item that says "Switch Tenant." From there, you will need to authorize the Auth0 Labs Extension with the correct tenant: labs-arcadia-rose-okta.
