### ISSUE TITLE
Step 12: Run the App -- Uh Oh!

### ISSUE THREAD

**Issue by brendaesco** [auth0-training/labs-node-create-an-application#30]
When I follow the instructions for Step #12 in this lab, I am expecting an error message: Callback URL mismatch with a link that I need to post in the Allowed Callback URLs in Auth0 dashboard, however, I am not getting any error message. I am following the steps detailed in the instructions exactly as detailed in the **Run the Application** section. When I click on **Open URL**, I get the page shown below (second screenshot). I know it says it might take a while for the error to show, but no matter how long I wait or how many times I go through the steps again, I am not seeing this error message. 

<img width="1469" alt="Screenshot 2024-07-22 at 1 51 49 PM" src="https://github.com/user-attachments/assets/505f51b8-128f-44b6-8518-70ab44bb5c85">
<img width="1471" alt="Screenshot 2024-07-22 at 1 51 58 PM" src="https://github.com/user-attachments/assets/ec4f2a39-96d2-4946-9c4a-2c20529d74d2">

**Comment by kazemicode** [comment]
Hi there. The issue is that you are not logged in to your Auth0 tenant via the Auth0 Labs Extension. Please see https://auth0-training.github.io/#i-signed-into-the-wrong-auth0-tenant
