### ISSUE TITLE
Port 7000 is not accesible by default in OSX Monterey

### ISSUE THREAD

**Issue by dlozlla** [auth0-training/labs-node-create-an-application#8]
### Description

The repo is ready to use port 7000 on localhost but this does not work by default at least in the new OSX Monterey version. The port seems to be used by Mac AirPlay service. I simply changed local env variables and config in package.json to use port 10000 .
### Reproduction

```
dlozlla@C02FG36NMD6P ~/Repos $ curl -v http://localhost:7000
*   Trying ::1:7000...
* Connected to localhost (::1) port 7000 (#0)
> GET / HTTP/1.1
> Host: localhost:7000
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Content-Length: 0
< Server: AirTunes/605.1
<
* Connection #0 to host localhost left intact
```

### Environment

- **Version of this library used:** 1.0.0
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** OSX Monterey
- **Other modules/plugins/libraries that might be involved:**

**Comment by NotMyself** [comment]
Should be resolved with the 1.1.1 release.
